services:
  db:
    image: mysql:8.0
    container_name: daehee-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: onboarding
      TZ: Asia/Seoul
    ports:
      - "3307:3306"  # 내 컴퓨터(3307) -> 도커(3306) 연결
    command: --default-time-zone=Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
